#include <iostream>
#include <utility>
#include <vector>
#include <set>
#include "Lexer.h"
#include "Interpreter.h"


Interpreter::Interpreter(const Environment& env) {
    this->env = env;
}

void Interpreter::interpret(const ASTNode *node) {
    if (!node) return;

    if (node->type == "PROGRAM") {
        for (auto& child : node->children) {
            executeRule(child);
        }
    }
    if (activatedFacts.empty()) {
        std::cout << "(no output)\n";
    } else {
        for (const std::string& fact : activatedFacts) {
            std::cout << fact << '\n';
        }
    }
    static_analysis(node);
    for (const std::string& msg : conflictMessages) {
        std::cout << "Conflict:\n" << msg << "\n";
    }

    for (const std::string& msg : redundancyMessages) {
        std::cout << "Redundant rules: " << msg << "\n";
    }

    for (const std::string& msg : inactiveRuleMessages) {
        std::cout << "Potentially inactive rule: " << msg << "\n";
    }
}

void Interpreter::executeRule(const ASTNode* ruleNode) {
    std::string ruleName = ruleNode->value;
    ASTNode* condN = ruleNode->children[0];
    ASTNode* actionN = ruleNode->children[1];

    if (condition(condN)) {
        act(actionN->value);
    } else unactivatedFacts.insert(ruleName);
}

bool Interpreter::fact(std::string x) {
    return env.getfact(x);
};

bool Interpreter::condAND(bool x, bool y) {
    return x && y;
}

bool Interpreter::condition(const ASTNode* condN) {
    if (!condN) return false;

    if (condN->type == "AND") {
        bool left = condition(condN->children[0]);
        bool right = condition(condN->children[1]);
        return condAND(left, right);
    }
    if (condN->type == "COND") {
        int left = env.getvar(condN->children[0]->value); //Obtiene valor asociado al ID
        std::string op = condN->children[1]->value; //Obtiene operador
        int right = std::stoi(condN->children[2]->value); //Convierte valor para comparar a entero
        return cmp(left, op, right);
    }
    if (condN->type == "FACT") {
        return fact(condN->children[0]->value);
    }
    return false;
}
bool Interpreter::cmp(const int& x, const std::string& op, const int& v) {
    if (op == ">") return x > v;
    if (op == "<") return x < v;
    if (op == "=") return x == v;
    return false;
}

void Interpreter::act(const std::string& id) {
    env.setfact(id);
    activatedFacts.insert(id);
}

void Interpreter::static_analysis(const ASTNode* root) {
    if (!root || root->type != "PROGRAM") return;

    std::map<std::string, std::vector<std::string>> ruleAct;
    const std::vector<ASTNode*>& rules = root->children;

    //Se agregan al mapa las reglas junto con las acciones que producen
    for (const ASTNode* ruleNode : rules) {
        std::string ruleName = ruleNode->value;
        std::string actionName = ruleNode->children[1]->value;
        ruleAct[actionName].push_back(ruleName);
    }
    //Se generan los mensajes de error en caso de encontrar conflictos
    for (const auto& pair : ruleAct) {
        if (pair.second.size() > 1) { //Es verdadero si hay un vector con varios valores (Más de una regla que produce la misma acción)
            std::string msg = "Action " + pair.first + " generated by ";
            for (size_t i = 0; i < pair.second.size(); ++i) {
                msg += pair.second[i] + (i < pair.second.size() - 1 ? ", " : "");
            }
            conflictMessages.push_back(msg);
        }
    }

    //Se detectan redundancias (misma condición y misma acción)
    for (size_t i = 0; i < rules.size(); ++i) {
        for (size_t j = i + 1; j < rules.size(); ++j) {
            std::string action1 = rules[i]->children[1]->value;
            std::string action2 = rules[j]->children[1]->value;

            if (action1 == action2) {
                //Si la acción es igual, se comparan las condiciones
                if (compareCond(rules[i]->children[0], rules[j]->children[0])) {
                    redundancyMessages.push_back(rules[i]->value + ", " + rules[j]->value);
                }
            }
        }
    }

    //Se detectan hechos potencialmente inactivos
    for (const auto& f: unactivatedFacts ) {
        inactiveRuleMessages.push_back(f);
    }
}

//Compara recursivamente los sub-árboles de condición
bool Interpreter::compareCond(const ASTNode* n1, const ASTNode* n2) {
    if (!n1 && !n2) return true;
    if (!n1 || !n2) return false;
    if (n1->type != n2->type) return false;

    if (n1->type == "AND") {
        return
            compareCond(n1->children[0], n2->children[0]) &&
            compareCond(n1->children[1], n2->children[1]);
    }
    if (n1->type == "COND") {
        return
            n1->children[0]->value == n2->children[0]->value && //Misma variable
            n1->children[1]->value == n2->children[1]->value && //Mismo operador
            n1->children[2]->value == n2->children[2]->value;   //Mismo valor
    }
    if (n1->type == "FACT") {
        return n1->children[0]->value == n2->children[0]->value;
    }
    return false;
}